export default [
    
    {
        id:1,
        role_name: 'iOS Developer',
        company: 'Apple',
        logo:'https://images.unsplash.com/photo-1637363990764-de84fd247b7d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        stipend:"10000",
        experience: 'fresher',
        location: 'Remote',
        type:"Intership",
    },
    {
        id: 2,
        role_name: "Frontend Developer",
        company: "Amazon",
        logo:"https://images.unsplash.com/photo-1649734926695-1b1664e98842?q=80&w=2062&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        stipend:"25000",
        experience: "Fresher",
        location: "In-office",
        type:"Intership",

        
      },
      {
        id: 3,
        
        role_name: "Android Developer",
        company: "Facebook",
        logo:"https://images.unsplash.com/photo-1706879349328-4a05bb3e16ea?q=80&w=1781&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        stipend:"15000",
        experience: "Senior Level",
        location: "Remote",
        type:"Intership",
      },
      {
        id: 4,
        role_name: "Software Developer",
        company: "Netflix",
        logo:"https://images.unsplash.com/photo-1637363990764-de84fd247b7d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 5,
        role_name: "Software Engineering (Backend)",
        company: "Impact Analytics",
        logo:"https://internshala-uploads.internshala.com/logo%2F7ddqy82i8jf-3066.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 6,
        role_name: "Laravel Development",
        company: "NetflQUARTERSTACK TECHNOLOGIES PRIVATE LIMITEDix",
        logo:"https://internshala-uploads.internshala.com/logo%2Ff5340sdhmzd-19114.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 7,
        role_name: "Python Development",
        company: "Weroute Systems Private Limited",
        logo:"https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.shutterstock.com%2Fshutterstock%2Fphotos%2F1960050976%2Fdisplay_1500%2Fstock-vector-blank-black-emblem-shield-with-straight-ribbon-1960050976.jpg&tbnid=25t9D_19qcPzKM&vet=12ahUKEwjpkbab0bmEAxX5cWwGHa74Dc8QMygEegQIARBc..i&imgrefurl=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fblank-logo-designs&docid=ZO1dQW5Jk_XFEM&w=1500&h=1300&q=blank%20company%20logo&ved=2ahUKEwjpkbab0bmEAxX5cWwGHa74Dc8QMygEegQIARBc",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 8,
        role_name: "React Native Development - Remote/WFH",
        company: "NetflQUARTERSTACK TECHNOLOGIES PRIVATE LIMITED",
        logo:"https://internshala-uploads.internshala.com/logo%2Ff5340sdhmzd-19114.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 9,
        role_name: "Software Development",
        company: "TerraBlu Climate Technologies Private Limited",
        logo:"https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.shutterstock.com%2Fshutterstock%2Fphotos%2F1960050976%2Fdisplay_1500%2Fstock-vector-blank-black-emblem-shield-with-straight-ribbon-1960050976.jpg&tbnid=25t9D_19qcPzKM&vet=12ahUKEwjpkbab0bmEAxX5cWwGHa74Dc8QMygEegQIARBc..i&imgrefurl=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fblank-logo-designs&docid=ZO1dQW5Jk_XFEM&w=1500&h=1300&q=blank%20company%20logo&ved=2ahUKEwjpkbab0bmEAxX5cWwGHa74Dc8QMygEegQIARBc",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 10,
        role_name: "Whatsapp Bot Creation",
        company: "Systemic Altruism",
        logo:"https://internshala-uploads.internshala.com/logo%2Fc2823plfoc_-28437.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 11,
        role_name: "Software Development Engineer (Android)",
        company: "Internshala",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e311f012fcb31580277505.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 12,
        role_name: "Flutter Development",
        company: "Internshala",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e311f012fcb31580277505.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 13,
        role_name: "Golang Development",
        company: "WiJungle - by HttpCart",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e6d26a59badc1584211621.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 14,
        role_name: "Computer Vision",
        company: "Indika AI Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F61531437975a51632834615.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 15,
        role_name: "Artificial Intelligence (AI)",
        company: "Skygoal",
        logo:"https://internshala-uploads.internshala.com/logo%2F61bae4f2765a51639638258.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 16,
        role_name: ".NET Development",
        company: "Radionics Technology",
        logo:"https://internshala-uploads.internshala.com/logo%2F63c824de12d841674061022.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 17,
        role_name: "Python Django",
        company: "Across The Globe (ATG)",
        logo:"https://internshala-uploads.internshala.com/logo%2F632b287d5668f1663772797.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 18,
        role_name: "Flutter Development",
        company: "Fringale",
        logo:"https://internshala-uploads.internshala.com/logo%2Fb3pgwca8566-19666.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 19,
        role_name: "Python Development",
        company: "Aiveda Technology",
        logo:"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c0840e59-db43-4681-ae7b-31a04dc4bc55/d7eqdvw-4e97ac92-e4b9-4498-9655-e4d612eb478b.png/v1/fill/w_1192,h_670/random_logo_by_criticl_d7eqdvw-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9OTAwIiwicGF0aCI6IlwvZlwvYzA4NDBlNTktZGI0My00NjgxLWFlN2ItMzFhMDRkYzRiYzU1XC9kN2VxZHZ3LTRlOTdhYzkyLWU0YjktNDQ5OC05NjU1LWU0ZDYxMmViNDc4Yi5wbmciLCJ3aWR0aCI6Ijw9MTYwMCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.X991O1jF5lTNZbbEoHEfoo6nlHEihBMHMIm5-uBCXcU",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 20,
        role_name: "Python Development",
        company: "Visual Verb",
        logo:"https://internshala-uploads.internshala.com/logo%2F63c06c61c3b9a1673555041.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 21,
        role_name: "Artificial Intelligence (AI)",
        company: "Kalyani Strategic Management Services",
        logo:"https://internshala-uploads.internshala.com/logo%2Ffh6vieuz8up-138115.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 22,
        role_name: "Software Development",
        company: "Elec Torq Technologies Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2Ffh4ji3wmwp3-11215.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 23,
        role_name: "Unreal Developer",
        company: "HEXR Factory",
        logo:"https://internshala-uploads.internshala.com/logo%2F62fdc589567f71660798345.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 24,
        role_name: "Flutter Development",
        company: "RNH Tech Group",
        logo:"https://internshala-uploads.internshala.com/logo%2F2vq3suz70c0-5914.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 25,
        role_name: "Manual And Automation Tester",
        company: "OrgLens Consultancy Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F611f46ee524ca1629439726.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 26,
        role_name: "Artificial Intelligence (AI)",
        company: "Buddha Education Association Incorporation",
        logo:"https://internshala.com/uploads/logo%2F5f5216193fc151599215129.gif",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 27,
        role_name: "Machine Learning",
        company: "Buddha Education Association Incorporation",
        logo:"https://internshala.com/uploads/logo%2F5f5216193fc151599215129.gif",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 28,
        role_name: "Software Development",
        company: "Cehpoint",
        logo:"https://internshala-uploads.internshala.com/logo%2F512tt4u8li8-11544.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 29,
        role_name: "Software Testing",
        company: "Myraana",
        logo:"https://internshala-uploads.internshala.com/logo%2F512tt4u8li8-11544.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 30,
        role_name: "Java Development",
        company: "Acuver Consulting",
        logo:"https://internshala-uploads.internshala.com/logo%2F64b8a1694db841689821545.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 31,
        role_name: "Artificial Intelligence (AI)",
        company: "Wonder Images Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F64b8a1694db841689821545.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 32,
        role_name: "Engineering",
        company: "Dataset Connect Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F7s7wg8hc8m6-3765.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 33,
        role_name: "Software Development",
        company: "Grofo",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e311f012fcb31580277505.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 34,
        role_name: "Software Development Engineering (Web)",
        company: "Internshala",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e311f012fcb31580277505.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 35,
        role_name: "Low Code Developer",
        company: "Gurpreet Seehra",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde93c8cf71580195475.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 36,
        role_name: "Software Development",
        company: "Mobillor Technologies Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde93c8cf71580195475.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 37,
        role_name: "Software Development",
        company: "Blackcoffer",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fdce8a376f1580195048.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 38,
        role_name: "Computert Vision",
        company: "Wobot Intelligence Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F64b7f376de81c1689777014.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 39,
        role_name: "Desktop Support Engineer",
        company: "IND Sphinx Precision Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F64b7f376de81c1689777014.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 40,
        role_name: "Software Development Engineering (Web)",
        company: "Neuman Works",
        logo:"https://internshala-uploads.internshala.com/logo%2F5f3e217c6b1ac1597907324.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 41,
        role_name: "Artificial Intelligence (AI)",
        company: "Logicboots Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F5fbf83b5e9b651606386613.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 42,
        role_name: "Software Development Engineering (Web)",
        company: "Aniket Maurya (London, United Kingdom)",
        logo:"https://internshala-uploads.internshala.com/logo%2F5f3e217c6b1ac1597907324.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 43,
        role_name: "Applied AI",
        company: "Systemic Altruism",
        logo:"https://internshala-uploads.internshala.com/logo%2Fc2823plfoc_-28437.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 44,
        role_name: "Flutter Development",
        company: "Systemic Altruism",
        logo:"https://internshala-uploads.internshala.com/logo%2Fc2823plfoc_-28437.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 45,
        role_name: "FlutterFlow (NO-Code DEV)",
        company: "Next You Labs",
        logo:"https://internshala-uploads.internshala.com/logo%2Fbo0mdx7wrjo-16514.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 46,
        role_name: "Software Product Management",
        company: "Reach Technologies",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde5143e461580195409.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 47,
        role_name: "Algorithm Development",
        company: "Reach Technologies",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde5143e461580195409.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 48,
        role_name: "Flutter Development",
        company: "Coding Junior",
        logo:"https://internshala-uploads.internshala.com/logo%2F6102971a851411627559706.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 49,
        role_name: "Python Development",
        company: "FynTune Solution Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F6102971a851411627559706.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 50,
        role_name: "AWS DevOps Engineert",
        company: "Rydeu Logistics UG",
        logo:"https://internshala-uploads.internshala.com/logo%2F5dffb7cf75b091577039823.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id:51,
        role_name: 'Python/Django Development',
        company: 'Shobhit Gupta',
        logo:'https://internshala.com/uploads/logo%2Fap910kp0b0s-73170.jpeg',
        stipend:"10000",
        experience: 'fresher',
        location: 'Remote',
        type:"Intership",
    },
    {
        id: 52,
        role_name: "Java Development",
        company: "Monkhub",
        logo:"https://internshala-uploads.internshala.com/logo%2F615e65210ed561633576225.png.webp",
        stipend:"25000",
        experience: "Fresher",
        location: "In-office",
        type:"Intership",

        
      },
      {
        id: 53,
        
        role_name: "AI Automation Testing",
        company: "Digite Infotech Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde89e81521580195465.png.webp",
        stipend:"15000",
        experience: "Senior Level",
        location: "Remote",
        type:"Intership",
      },
      {
        id: 54,
        role_name: "Software Development",
        company: "Fastech Automations",
        logo:"https://internshala-uploads.internshala.com/logo%2F6350fbd785e641666251735.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 55,
        role_name: "Python Development",
        company: "Analystt.ai",
        logo:"https://internshala-uploads.internshala.com/logo%2F6350fbd785e641666251735.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 56,
        role_name: "Game Development",
        company: "MentorBoxx",
        logo:"https://internshala-uploads.internshala.com/logo%2F6098d939ed54d1620629817.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 57,
        role_name: "Computer Vision",
        company: "Indika AI Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F61531437975a51632834615.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 58,
        role_name: "Prompt Engineering",
        company: "DeepThought Edutech Ventures Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F61e3eea71c3231642327719.jpg.webp",
        stipend:"2000",
        experience: "fresher",
        location: "On-site",
        type:"Intership",
      },
      {
        id: 59,
        role_name: "AI Content Creation",
        company: "DeepThought Edutech Ventures Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F61e3eea71c3231642327719.jpg.webp",
        stipend:"2000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 60,
        role_name: "Flutter Development",
        company: "Ostello India Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F6476daf61d4511685510902.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 61,
        role_name: "Flutter Development",
        company: "EpiGle",
        logo:"",
        stipend:"3200",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 62,
        role_name: "Python Development",
        company: "Webknot Technologies Private Limited",
        logo:"",
        stipend:"3500",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 63,
        role_name: "Flutter Development",
        company: "Blackcoffer",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fdce8a376f1580195048.png.webp",
        stipend:"5000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 64,
        role_name: "Flutterflow Developer",
        company: "Madrocket Technologies & Media",
        logo:"https://internshala-uploads.internshala.com/logo%2F63a95c5bdc4d11672043611.jpg.webp",
        stipend:"10000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 65,
        role_name: "Embedded Systems And Software Development (Full Stack From Design To Deploy, IoT , AI/ML)",
        company: "Oralens LLC (Sheridan, United States)",
        logo:"https://internshala-uploads.internshala.com/logo%2F61531437975a51632834615.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 66,
        role_name: "Software Development",
        company: "Indika AI Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F61531437975a51632834615.png.webp",
        stipend:"10000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 67,
        role_name: "Artificial Intelligence (AI)",
        company: "Indika AI Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F61531437975a51632834615.png.webp",
        stipend:"7000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 68,
        role_name: "AI/ML Engineer Intern",
        company: "Isourse",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde68c46a41580195432.png.webp",
        stipend:"20000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 69,
        role_name: "Software Development",
        company: "Quantta Analytics",
        logo:"https://internshala-uploads.internshala.com/logo%2F649a9b462e1361687853894.jpg.webp",
        stipend:"8000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 70,
        role_name: "Software Project Management",
        company: "Ollosoft Technologies Private Limited",
        logo:"https://internshala.com/uploads/logo%2F5e2fddbd904181580195261.bmp",
        stipend:"10000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 71,
        role_name: "React Native Development",
        company: "Across The Globe (ATG)",
        logo:"https://internshala-uploads.internshala.com/logo%2F632b287d5668f1663772797.jpg.webp",
        stipend:"5000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 72,
        role_name: "Game Designer Skating AAA Video Game",
        company: "MBS STUDIOS PRIVATE LIMITED",
        logo:"https://internshala-uploads.internshala.com/logo%2F5eqgynxoome-41257.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 73,
        role_name: "Game Development",
        company: "Jayam Patel",
        logo:"  https://internshala-uploads.internshala.com/logo%2F5e2fde705beab1580195440.png.webp",
        stipend:"8000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 74,
        role_name: "Software Development",
        company: "Arpita Saha",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde705beab1580195440.png.webp",
        stipend:"5000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 75,
        role_name: "Software Development",
        company: "Innovaccer Analytics Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde705beab1580195440.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 76,
        role_name: "Conent Development And Robotics Trainer",
        company: "Yolabs",
        logo:"https://internshala-uploads.internshala.com/logo%2F60549aaf583091616157359.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 77,
        role_name: "AI - Natural Language Processing (NLP)",
        company: "Technoculture Research",
        logo:"https://internshala-uploads.internshala.com/logo%2F63a15a0e3fd761671518734.png.webp",
        stipend:"18000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 78,
        role_name: "Flutter Flow Expert",
        company: "Jharkhand IT Solutions",
        logo:"https://internshala-uploads.internshala.com/logo%2F29y71n4uwn0-3643.png.webp",
        stipend:"19000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 79,
        role_name: "React Native Development",
        company: "Technoculture Research",
        logo:"https://internshala-uploads.internshala.com/logo%2F63a15a0e3fd761671518734.png.webp",
        stipend:"12000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 80,
        role_name: "Python Development",
        company: "TIIM",
        logo:"https://internshala-uploads.internshala.com/logo%2F63a93d572952e1672035671.png.webp",
        stipend:"4000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 81,
        role_name: "Artificial Intelligence (AI)",
        company: "Wonder Images Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F64b8a1694db841689821545.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 82,
        role_name: "Engineering",
        company: "Dataset Connect Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F7s7wg8hc8m6-3765.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 83,
        role_name: "Software Development",
        company: "Grofo",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e311f012fcb31580277505.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 84,
        role_name: "Software Development Engineering (Web)",
        company: "Internshala",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e311f012fcb31580277505.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 85,
        role_name: "Low Code Developer",
        company: "Gurpreet Seehra",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde93c8cf71580195475.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 86,
        role_name: "Software Development",
        company: "Mobillor Technologies Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde93c8cf71580195475.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 87,
        role_name: "Software Development",
        company: "Blackcoffer",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fdce8a376f1580195048.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 88,
        role_name: "Computert Vision",
        company: "Wobot Intelligence Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F64b7f376de81c1689777014.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 89,
        role_name: "Desktop Support Engineer",
        company: "IND Sphinx Precision Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F64b7f376de81c1689777014.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 90,
        role_name: "Software Development Engineering (Web)",
        company: "Neuman Works",
        logo:"https://internshala-uploads.internshala.com/logo%2F5f3e217c6b1ac1597907324.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 91,
        role_name: "Artificial Intelligence (AI)",
        company: "Logicboots Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F5fbf83b5e9b651606386613.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 92,
        role_name: "Software Development Engineering (Web)",
        company: "Aniket Maurya (London, United Kingdom)",
        logo:"https://internshala-uploads.internshala.com/logo%2F5f3e217c6b1ac1597907324.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 93,
        role_name: "Applied AI",
        company: "Systemic Altruism",
        logo:"https://internshala-uploads.internshala.com/logo%2Fc2823plfoc_-28437.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 94,
        role_name: "Flutter Development",
        company: "Systemic Altruism",
        logo:"https://internshala-uploads.internshala.com/logo%2Fc2823plfoc_-28437.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 95,
        role_name: "FlutterFlow (NO-Code DEV)",
        company: "Next You Labs",
        logo:"https://internshala-uploads.internshala.com/logo%2Fbo0mdx7wrjo-16514.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 96,
        role_name: "Software Product Management",
        company: "Reach Technologies",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde5143e461580195409.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 97,
        role_name: "Algorithm Development",
        company: "Reach Technologies",
        logo:"https://internshala-uploads.internshala.com/logo%2F5e2fde5143e461580195409.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 98,
        role_name: "Flutter Development",
        company: "Coding Junior",
        logo:"https://internshala-uploads.internshala.com/logo%2F6102971a851411627559706.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 99,
        role_name: "Python Development",
        company: "FynTune Solution Private Limited",
        logo:"https://internshala-uploads.internshala.com/logo%2F6102971a851411627559706.png.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
      {
        id: 100,
        role_name: "AWS DevOps Engineert",
        company: "Rydeu Logistics UG",
        logo:"https://internshala-uploads.internshala.com/logo%2F5dffb7cf75b091577039823.jpg.webp",
        stipend:"30000",
        experience: "Junior Level",
        location: "Hybrid",
        type:"Intership",
      },
]